package com.prodapt.license_tracker_backend.entities.enums;

public enum AlertType {
    LICENSE_EXPIRING,
    LICENSE_EXPIRED,
    LICENSE_CAPACITY_WARNING,
    LICENSE_CAPACITY_CRITICAL,
    DEVICE_LIFECYCLE_WARNING,
    SOFTWARE_VERSION_OUTDATED,
    SOFTWARE_VERSION_CRITICAL,
    COMPLIANCE_VIOLATION,
    ASSIGNMENT_FAILED,
    SYSTEM_NOTIFICATION
}
